# This is a basic workflow to show the manual trigger
name: Release-Action-Workflow
on: 
  push:
    branches:
      - main
      - release_v*
  pull_request:
    branches:
      - main
      - release_v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
     
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
        
      - name: Running on the default branch.
        if: steps.branch-name.outputs.is_default == 'true'
        run: |
          echo "Running on default: ${{ steps.branch-name.outputs.current_branch }}"
        # Outputs: "Running on default: main".
      
      - name: Running on a pull request branch.
        if: steps.branch-name.outputs.is_default == 'true'
        run: |
          echo "Running on pr: ${{ steps.branch-name.outputs.current_branch }}"
          pwd
        # Outputs: "Running on pr: feature/test".
        
      - name: Read Services from file
        id: template
        uses: traversals-analytics-and-intelligence/file-reader-action@master
        with:
          file: ./services.yaml

      - name: Echo services list
        run: echo "${{ steps.template.outputs.content }}"
