# This is a basic workflow to show the manual trigger
name: Release-Actions-Workflow

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
        
      - name: Running on the default branch.
        if: steps.branch-name.outputs.is_default == 'true'
        run: |
          echo "Running on default: ${{ steps.branch-name.outputs.current_branch }}"
        # Outputs: "Running on default: main".
      
      - name: Running on a pull request branch.
        if: steps.branch-name.outputs.is_default == 'true'
        run: |
          echo "Running on pr: ${{ steps.branch-name.outputs.current_branch }}"
        # Outputs: "Running on pr: feature/test".
        
      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./services.yaml

      - name: Echo package.json
        run: echo "${{ steps.package.outputs.content }}"
